# Working directory
root = "."
tmp_dir = "tmp"

[build]
# Command to build the project
cmd = "go build -o ./tmp/main ./cmd/main.go"
# Binary output file path
bin = "./tmp/main"

# Watch these directories for changes
include_ext = ["go", "tpl", "tmpl", "html"]

# Exclude these directories from being watched
exclude_dir = ["vendor", "tmp"]

# Delay before rebuilding the project
delay = 1000

[log]
# Log color
color = "true"
# Log level: debug, info, warn, error, fatal, panic
level = "info"

[dev]
# File to write PID of the running process
pid_file = "tmp/air.pid"
